name: Pull and Run Docker Image

on:
  workflow_run:
        workflows: ['SampleFlow']
        types: [completed]

jobs:
  check-docker-build-workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"
  fail-job:    
    needs: check-docker-build-workflow
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
    - name: fail the job
      run: | 
          echo "First Workflow failed."
          exit 1
