name: Docker Image CI

on:
  push:
    branches: [ "mainnn" ]
  pull_request:
    branches: [ "mainnn" ]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create model
        run:
          python train.py

      - name: Test model
        run: |
          OUTPUT=$(python test.py)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.329" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
  build:  
    needs: [evaluate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chphanisaisriram/test_repo1:SampleDockerImage_1
