name: Pull-Image-And-Test-Reusable
on:
  workflow_call:

jobs:
  Docker-Build-Success:
    runs-on: ubuntu-latest
    steps:
      # Check out the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Pull the Docker image only if the Parent workflow got Succeeded
      - name: Pull Docker image
        run: echo "Starting to pull Latest Docker Image"

      - name: Run the image
        run: |
          OUTPUT=$(docker run chphanisaisriram/mlops:ci_cd_v1)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.35" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
          echo "test.py script executed Successfully."
