name: TrainAndBuildDocker_test

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
#This job is to build the Docker file and push it to a docker repository
  build_docker:

    runs-on: ubuntu-latest

    steps:
        #Check out the latest code
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Login to Docker Hub
        #This action builds the Docker image and pushes to the docker repository. Single action takes care of this activity
        uses: docker/login-action@v2 #Login to Docker 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # User Name and Token are stored in GitHub Secrets.
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          echo "Sample"
          
  call-re-usable-workflow:
    runs-on: ubuntu-latest
    needs: build_docker
    if: ${{ needs.build_docker.result == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./.github/workflows/pull_docker_reusable.yml@main
  fail-job:
      runs-on: ubuntu-latest  
      needs: build_docker
      if: ${{ failure() }}
      steps:
      - name: fail the jobs as docker image build job is failed
        run: |
          echo "Fail the job since the docker job to build and push docker image job got failed"
          exit 1 
