name: TrainAndBuildDocker
on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
#This job is to build the Docker file
  build_docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3    
      - name: Login to Docker Hub
        uses: docker/login-action@v2 #Login to Docker 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # User Name and Token are stored in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4 #This actions builds and pushes the docker image
        with:
          push: true
          tags: chphanisaisriram/mlops:ci_cd_v1 #Docker Repo Name
          
